name: new_120h/reload_long
neptune_project_name: rpose
offline_mode: false
timestamp: true
weights_restore: true
checkpoint_load: cluster_run_24h/reload/Checkpoint-epoch=37--step=094999.ckpt  #6_restart/2021-04-16T18:34:09_12_iteartions_4_real_finetuning_real/last.ckpt
weights_restore_seg: true
checkpoint_load_seg: seg_exp/24h_long_run_fully_working/last.ckpt
checkpoint_restore: false

mode: train
lr: 0.0001
tag_list:
  - flow_estimation
  - new_syn_data

logged_images_max:
  train: 10
  val: 10
  test: 10
log:
  individual_obj:
    train: True
    val: True
    test: True
full_pose_estimation:
  flow_to_trafo_PnP:
    method: solvePnPRefineLM
    reprojectionError: 3
    iterationsCount: 100
  trust_region: 0.1

# Standard Setting
lr_scheduler:
  active: true
  name: POLY
  poly_cfg:
    power: 0.9
    max_epochs: 100
    target_lr: 1.0e-06
  onecyclelr_cfg:
    num_steps: 50000

optimizer:
  name: WADAM
  sgd_cfg:
    momentum: 0.9
    weight_decay: 4.0e-05
  wadam_cfg:
   weight_decay: 0.00001 
   eps: 1.0e-08

trainer:
  precision: 16
  accumulate_grad_batches: 1
  fast_dev_run: false
  limit_train_batches: 5000
  limit_val_batches: 500
  limit_test_batches: 1.0
  progress_bar_refresh_rate: 10
  max_epochs: 1000
  gpus: -1
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  profiler: False
  accelerator: ddp

seg:
  name: Fast-SCNN
  cfg:
    num_classes: 2
    aux: false
    extraction:
      active: false
      layer: 'learn_to_down'
    input_channels: 6

model:
  name: RPOSE
  args:
    small: False
  gamma: 0.85
  iters: 12

cb_early_stopping:
  active: false
  cfg:
    monitor: val_loss_epoch
    patience: 10000
    strict: true
    verbose: true
    mode: min
    min_delta: -0.0001

cb_checkpoint:
  active: true
  nameing: 1
  cfg:
    verbose: true
    monitor: train_loss
    mode: min
    prefix: ''
    save_last: true
    save_top_k: 1    

train_dataset:
  stage: ycb
  image_size:
    - 480
    - 640
  mode: train_new_syn
  cfg_ycb:
    init_mode: noise
    expand_factor: 1.3
    aug_params:
       crop_size:
       - 480
       - 640
       min_scale: -0.2
       max_scale: 0.4
       do_flip: True
    output_cfg:
      noise_translation: 0.03
      noise_rotation: 30
    ratio:
      data: 1 #keep this to 1 fixed
      data_syn: 1
      data_syn_new: 1

  loader:
    pin_memory: true
    batch_size: 5
    shuffle: true
    num_workers: 20

val_dataset:
  stage: ycb
  image_size:
    - 480
    - 640
  mode: test
  cfg_ycb:
    init_mode: noise
    expand_factor: 1.3
    aug_params:
       crop_size:
       - 480
       - 640
       min_scale: -0.2
       max_scale: 0.4
       do_flip: True
    output_cfg:
      noise_translation: 0.03
      noise_rotation: 30
  loader:
    pin_memory: true
    batch_size: 5
    shuffle: false
    num_workers: 20

test_dataset:
  stage: ycb
  image_size:
    - 480
    - 640
  mode: test
  cfg_ycb:
    init_mode: noise
    expand_factor: 1.1
    aug_params:
       crop_size:
       - 480
       - 640
       min_scale: -0.2
       max_scale: 0.4
       do_flip: False
    output_cfg:
      noise_translation: 0.03
      noise_rotation: 30
  loader:
    pin_memory: true
    batch_size: 1
    shuffle: false
    num_workers: 0
    
lr_monitor:
  cfg:
    logging_interval: step

move_datasets:
- ycb
- data_syn_new
