name: evaluate/high_noise_3_days_training
neptune_project_name: rpose
offline_mode: false
timestamp: true
weights_restore: false
weights_restore2: true

checkpoint_restore: false
checkpoint_load: high_noise_72h_intermediate/2021-04-11T08:35:56_poly_correct_lr/2021-04-11T08:35:56_poly_correct_lr/Checkpoint-epoch=116--step=292499.ckpt
# low_noise_24h/2021-04-11T08:41:29_low_noise/Checkpoint-epoch=28--step=072499.ckpt
# high_noise_72h_intermediate/2021-04-11T08:35:56_poly_correct_lr/last.ckpt
mode: test
lr: 0.0003
tag_list:
  - flow_estimation

full_pose_estimation:
  flow_to_trafo_PnP:
    method: solvePnPRefineLM
    reprojectionError: 3
    iterationsCount: 25

# Standard Setting
lr_scheduler:
  active: true
  name: POLY
  poly_cfg:
    power: 0.8
    max_epochs: 75
    target_lr: 5.0e-06
  onecyclelr_cfg:
    num_steps: 50000

optimizer:
  name: WADAM
  sgd_cfg:
    momentum: 0.9
    weight_decay: 4.0e-05
  wadam_cfg:
   weight_decay: 0.00001 
   eps: 1.0e-08

trainer:
  precision: 16
  accumulate_grad_batches: 1
  fast_dev_run: false
  limit_train_batches: 2500
  limit_val_batches: 250
  limit_test_batches: 1.0
  progress_bar_refresh_rate: 10
  max_epochs: 1000
  gpus: -1
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  profiler: False
  # accelerator: ddp

model:
  name: RPOSE
  args:
    small: False
  gamma: 0.85
  iters: 12

cb_early_stopping:
  active: false
  cfg:
    monitor: val_loss_epoch
    patience: 10000
    strict: true
    verbose: true
    mode: min
    min_delta: -0.0001

cb_checkpoint:
  active: true
  nameing: 1
  cfg:
    verbose: true
    # monitor: train_loss
    # mode: min
    prefix: ''
    save_last: true
    # save_top_k: 3  

train_dataset:
  stage: ycb
  image_size:
    - 480
    - 640
  mode: train
  cfg_ycb:
    aug_params:
       crop_size:
       - 480
       - 640
       min_scale: -0.2
       max_scale: 0.4
       do_flip: True
    output_cfg:
      noise_translation: 0.01
      noise_rotation: 20
  loader:
    pin_memory: true
    batch_size: 5
    shuffle: true
    num_workers: 16

val_dataset:
  stage: ycb
  image_size:
    - 480
    - 640
  mode: val
  cfg_ycb:
    aug_params:
       crop_size:
       - 480
       - 640
       min_scale: -0.2
       max_scale: 0.4
       do_flip: True
    output_cfg:
      noise_translation: 0.01
      noise_rotation: 20  
  loader:
    pin_memory: true
    batch_size: 5
    shuffle: false
    num_workers: 16

test_dataset:
  stage: ycb
  image_size:
    - 480
    - 640
  mode: test
  cfg_ycb:
    aug_params:
       crop_size:
       - 480
       - 640
       min_scale: -0.2
       max_scale: 0.4
       do_flip: True
    output_cfg:
      noise_translation: 0.01
      noise_rotation: 40

# train_dataset:
#   stage: kitti
#   image_size:
#     - 288
#     - 960
#   mode: train
#   cfg_ycb:
#     aug_params:
#        crop_size:
#        - 288
#        - 960
#        min_scale: -0.2
#        max_scale: 0.4
#        do_flip: True
#     output_cfg:
#       noise_translation: 0.02
#       noise_rotation: 30      
  loader:
    pin_memory: true
    batch_size: 1
    shuffle: true
    num_workers: 8
    
lr_monitor:
  cfg:
    logging_interval: step

move_datasets:
- ycb
