name: debug/r
neptune_project_name: rpose
offline_mode: false
timestamp: true
weights_restore: false
checkpoint_restore: false
checkpoint_load: test
lr: 0.003
tag_list:
  - flow_estimation

# Standard Setting
lr_scheduler:
  active: true
  cfg:
    power: 0.9
    max_epochs: 200
    target_lr: 1.0e-05

optimizer:
  name: ADAM
  sgd_cfg:
    momentum: 0.9
    weight_decay: 4.0e-05

trainer:
  precision: 16
  accumulate_grad_batches: 1
  fast_dev_run: false
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  progress_bar_refresh_rate: 1
  max_epochs: 1000
  gpus: -1
  accelerator: ddp
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  profiler: False

loader:
  pin_memory: true
  batch_size: 16
  shuffle: true
  num_workers: 16

model:
  name: RPOSE
  cfg:
    hidden_dim:
    context_dim:
    dropout: 
    alternate_corr:
    corr_radius:
    corr_levels:


cb_checkpoint:
  active: true
  nameing: 1
  cfg:
    verbose: true
    monitor: train_loss
    mode: min
    prefix: ''
    save_last: true
    save_top_k: 1    

lr_monitor:
  cfg:
    logging_interval: step

# IGNORE AT THE MOMENT
move_datasets:
  # - env_var: coco
  - env_var: scannet
