name: /home/jonfrey/results/debug/2021-03-03T18:31:59_r
neptune_project_name: rpose
offline_mode: true
timestamp: true
weights_restore: false
checkpoint_restore: false
checkpoint_load: test
lr: 2.0e-05
tag_list:
- flow_estimation
lr_scheduler:
  active: true
  cfg:
    power: 0.9
    max_epochs: 200
    target_lr: 1.0e-06
optimizer:
  name: ADAM
  sgd_cfg:
    momentum: 0.9
    weight_decay: 4.0e-05
trainer:
  precision: 16
  accumulate_grad_batches: 1
  fast_dev_run: false
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  progress_bar_refresh_rate: 1
  max_epochs: 1000
  gpus: 2
  accelerator: ddp
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  profiler: false
model:
  name: RPOSE
  args:
    hello: TEST
    small: false
cb_early_stopping:
  active: false
  cfg:
    monitor: val_loss_epoch
    patience: 10000
    strict: true
    verbose: true
    mode: min
    min_delta: -0.0001
cb_checkpoint:
  active: true
  nameing: 1
  cfg:
    verbose: true
    monitor: train_loss
    mode: min
    prefix: ''
    save_last: true
    save_top_k: 1
train_dataset:
  stage: kitti
  image_size:
  - 384
  - 512
  mode: train
  loader:
    pin_memory: true
    batch_size: 6
    shuffle: true
    num_workers: 4
lr_monitor:
  cfg:
    logging_interval: step
move_datasets:
- env_var: scannet
