from enum import Enum


class Violation(Enum):
  UNKNOWN = -1
  DATALOADER_OBJECT_INVALID = 0
  TRUST_REGION_CONSTRAINT = 1
  MINIMAL_NR_VALID_CONSTRAINT = 2
  INLIER_RATIO_CONSTRAINT = 3
  SUCCESS = 4
  TRANS_DIFFERENCE = 6
  ROT_DIFFERENCE = 7
  FAILED_R_REPRO = 8
