name: first_run_24h/augmentation
neptune_project_name: rpose
offline_mode: false
timestamp: true
weights_restore: true

checkpoint_restore: false
checkpoint_load: models/raft-kitti.pth
lr: 0.0001
tag_list:
  - flow_estimation

# Standard Setting
lr_scheduler:
  active: true
  name: OneCycleLR
  poly_cfg:
    power: 0.9
    max_epochs: 200
    target_lr: 1.0e-06
  onecyclelr_cfg:
    num_steps: 50000

optimizer:
  name: WADAM
  sgd_cfg:
    momentum: 0.9
    weight_decay: 4.0e-05
  wadam_cfg:
   weight_decay: 0.00001 
   eps: 1.0e-08

trainer:
  precision: 16
  accumulate_grad_batches: 1
  fast_dev_run: false
  limit_train_batches: 2500
  limit_val_batches: 250
  limit_test_batches: 1.0
  progress_bar_refresh_rate: 10
  max_epochs: 1000
  gpus: -1
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  profiler: False

model:
  name: RPOSE
  args:
    hello: TEST
    small: False
    # hidden_dim: 5
    # context_dim: 5
    # dropout: 0.1
    # alternate_corr: 5
    # corr_radius: 5
    # corr_levels: 5
  gamma: 0.85
  iters: 12

cb_early_stopping:
  active: false
  cfg:
    monitor: val_loss_epoch
    patience: 10000
    strict: true
    verbose: true
    mode: min
    min_delta: -0.0001

cb_checkpoint:
  active: true
  nameing: 1
  cfg:
    verbose: true
    monitor: train_loss
    mode: min
    prefix: ''
    save_last: true
    save_top_k: 1    

train_dataset:
  stage: ycb
  image_size:
    - 480
    - 640
  mode: train
  cfg_ycb:
    aug_params:
       crop_size:
       - 480
       - 640
       min_scale: -0.2
       max_scale: 0.4
       do_flip: True
    output_cfg:
      noise_translation: 0.02
      noise_rotation: 30  
  loader:
    pin_memory: true
    batch_size: 5
    shuffle: true
    num_workers: 16

val_dataset:
  stage: ycb
  image_size:
    - 480
    - 640
  mode: val
  cfg_ycb:
    aug_params:
       crop_size:
       - 480
       - 640
       min_scale: -0.2
       max_scale: 0.4
       do_flip: True
    output_cfg:
      noise_translation: 0.02
      noise_rotation: 30    
  loader:
    pin_memory: true
    batch_size: 5
    shuffle: false
    num_workers: 16


# train_dataset:
#   stage: kitti
#   image_size:
#     - 288
#     - 960
#   mode: train
#   cfg_ycb:
#     aug_params:
#        crop_size:
#        - 288
#        - 960
#        min_scale: -0.2
#        max_scale: 0.4
#        do_flip: True
#     output_cfg:
#       noise_translation: 0.02
#       noise_rotation: 30      


    
lr_monitor:
  cfg:
    logging_interval: step

# IGNORE AT THE MOMENT
move_datasets:
- ycb
