name: seg_exp/4h_test_run
neptune_project_name: rpose
offline_mode: false
timestamp: true
weights_restore: false
weights_restore2: false

checkpoint_restore: false
checkpoint_load: 3_full_training/2021-04-11T08:35:56_poly_correct_lr/last.ckpt

mode: train
lr: 0.0005
tag_list:
  - SEGMENTATION

# Standard Setting
# lr_scheduler:
#   active: true
#   name: POLY
#   poly_cfg:
#     power: 0.8
#     max_epochs: 50
#     target_lr: 1.0e-06
#   onecyclelr_cfg:
#     num_steps: 50000

# optimizer:
#   name: WADAM
#   sgd_cfg:
#     momentum: 0.9
#     weight_decay: 4.0e-05
#   wadam_cfg:
#    weight_decay: 0.00001 
#    eps: 1.0e-08
model:
  name: Fast-SCNN
  input_size:
    - 320
    - 640
  cfg:
    num_classes: 2
    aux: false
    extraction:
      active: false
      layer: 'learn_to_down'
    input_channels: 6

lr_scheduler:
  active: true
  cfg:
    power: 0.9
    max_epochs: 50
    target_lr: 1.0e-06
optimizer:
  name: ADAM
  sgd_cfg:
    momentum: 0.9
    weight_decay: 4.0e-05

trainer:
  precision: 16
  accumulate_grad_batches: 1
  fast_dev_run: false
  limit_train_batches: 10000
  limit_val_batches: 1000
  limit_test_batches: 1.0
  progress_bar_refresh_rate: 10
  max_epochs: 1000
  gpus: -1
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  profiler: False
  # accelerator: ddp

cb_early_stopping:
  active: false
  cfg:
    monitor: val_loss_epoch
    patience: 10000
    strict: true
    verbose: true
    mode: min
    min_delta: -0.0001

cb_checkpoint:
  active: true
  nameing: 1
  cfg:
    verbose: true
    # monitor: train_loss
    # mode: min
    prefix: ''
    save_last: true
    # save_top_k: 3  

train_dataset:
  stage: ycb
  image_size:
    - 480
    - 640
  mode: train
  cfg_ycb:
    aug_params:
       crop_size:
       - 480
       - 640
       min_scale: -0.2
       max_scale: 0.4
       do_flip: True
    output_cfg:
      noise_translation: 0.025
      noise_rotation: 45 
  loader:
    pin_memory: true
    batch_size: 8
    shuffle: true
    num_workers: 32

val_dataset:
  stage: ycb
  image_size:
    - 480
    - 640
  mode: val
  cfg_ycb:
    aug_params:
       crop_size:
       - 480
       - 640
       min_scale: -0.2
       max_scale: 0.4
       do_flip: True
    output_cfg:
      noise_translation: 0.025
      noise_rotation: 45   
  loader:
    pin_memory: true
    batch_size: 8
    shuffle: false
    num_workers: 32

test_dataset:
  stage: ycb
  image_size:
    - 480
    - 640
  mode: test
  cfg_ycb:
    aug_params:
       crop_size:
       - 480
       - 640
       min_scale: -0.2
       max_scale: 0.4
       do_flip: True
    output_cfg:
      noise_translation: 0.02
      noise_rotation: 45  
  loader:
    pin_memory: true
    batch_size: 8
    shuffle: true
    num_workers: 32
    
lr_monitor:
  cfg:
    logging_interval: step

move_datasets:
- ycb
